@baseUrl=http://localhost:7010

### Create new blog

POST {{baseUrl}}/blogs/create
Content-Type: application/json

{
  "name": "Christmas blog",
  "SiteUri": "https://christmas-blog.nonexisting"
}

### List all blogs
GET {{baseUrl}}/blogs/list-all
