version: '3.5'

services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DBNAME: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
      