services:
  postgres:
    image: postgres:17.0
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DBNAME: postgres
    ports:
      - ${POSTGRES_PORT}:5432
